language: php

php:
  - 5.6
  - 5.5
  - 5.4

before_script:
  - echo -e "\n\n\n\n\n" | pecl install -f event
  - echo "extension=event.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --dev --no-interaction --prefer-dist

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml